import React from 'react'

export const metadata = {
	title: 'Projects',
	description: 'Generated by create next app'
}

export default function ProjectLayout({children}: {children: React.ReactNode}) {
	return <>{children}</>
}
