import './style/style.css'
import {JetBrains_Mono} from 'next/font/google'
import Footer from './components/Footer'
import bg from './img/bg.jpg'
import Image from 'next/image'
import Header from './components/Header'

const jetBrains = JetBrains_Mono({subsets: ['latin']})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang='en'>
			<body className={jetBrains.className}>
				<div className='bgWrap'>
					<Image src={bg} alt='background' />
				</div>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}
